### ISSUE TITLE
A compiler error

### ISSUE THREAD

**Issue by jqz41401** [b4rtik/SharpKatz#4]
hello，i use command this compiler，but it report error
 C:\Windows\Microsoft.NET\Framework64\v3.5\csc.exe -define:DEBUG -optimize -out:katz.exe *.cs

OSVersionHelper.cs(12,14): error CS1518:  class、delegate、enum、interface
OSVersionHelper.cs(13,14): error CS1518:  class、delegate、enum、interface 
OSVersionHelper.cs(14,14): error CS1518:  class、delegate、enum、interface

**Comment by rakjong** [comment]
me too

**Comment by b4rtik** [comment]
Consider to use msbuild instead of csc.

Something like 

`msbuild SharpKatz.sln  /p:Configuration="Release" /p:Platform="Any CPU"`
