### ISSUE TITLE
Nothing to do

### ISSUE THREAD

**Issue by ghost** [b4rtik/SharpKatz#9]

**Comment by PureLittleWood** [comment]
> LogonSessions.cs line 77 `current = Utility.GetIntPtr(hLsass, lsasrvMem, logonSessionListSignOffset, oshelper.LOGONSESSIONLISTOFFSET + (8 * i));`
> 
> **I think, it may be 16 nor 8 because it's the head node pointer of one LogonSessionList which contains flink and blink.**
> 
> I tested it on windows server 2016(build 14393). The process may not stop on step 1 for the reason current will not equal to pList. I tested it on windows 10, and success. It should for the reason that there is only one LogonSessionList.
> 
> I change 8 to 16, and it will stop. But i do not have the correct result sometimes. I get NULL pointer for step1, step2 and so on. It will success only when the logon session of the token is in step0.
> 
> Hoping for your solution for this or correction for my statement
